-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 19:24:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bdm` ;

-- -----------------------------------------------------
-- Table `bdm`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`admin` (
  `IdAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdAdmin`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`producto` (
  `IdProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Unidades` INT(11) NOT NULL,
  `Fecha de Publicacion` TIMESTAMP NOT NULL,
  `Video` VARCHAR(45) NOT NULL,
  `Visitas` VARCHAR(45) NOT NULL,
  `Compras` VARCHAR(45) NOT NULL,
  `Oferta` VARCHAR(45) NOT NULL,
  `Publicado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`usuario` (
  `IdUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre de Usuario` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT(20) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Imagen` BLOB NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `Nombre de Usuario_UNIQUE` (`Nombre de Usuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`calificacion` (
  `IdProducto` INT(11) NOT NULL,
  `IdUsuario` INT(11) NOT NULL,
  `Calificacion` INT(11) NOT NULL,
  PRIMARY KEY (`IdProducto`, `IdUsuario`),
  INDEX `IdUsuario_idx` (`IdUsuario` ASC) VISIBLE,
  CONSTRAINT `IdProducto`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `bdm`.`producto` (`IdProducto`),
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `bdm`.`usuario` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`categoria` (
  `IdCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCategoria`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`chat` (
  `IdUsuario` INT(11) NOT NULL,
  `IdAdmin` INT(11) NOT NULL,
  `Mensaje` TEXT NULL DEFAULT NULL,
  `Precio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdUsuario`, `IdAdmin`),
  INDEX `IdAdmin_idx` (`IdAdmin` ASC) VISIBLE,
  CONSTRAINT `Admin`
    FOREIGN KEY (`IdAdmin`)
    REFERENCES `bdm`.`admin` (`IdAdmin`),
  CONSTRAINT `Usuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `bdm`.`usuario` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`compras` (
  `IdProducto` INT(11) NOT NULL,
  `IdUsuario` INT(11) NOT NULL,
  `IdAdmin` INT(11) NOT NULL,
  `Precio` INT(11) NOT NULL,
  `Fecha` TIMESTAMP NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `Carrito` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdProducto`, `IdUsuario`, `IdAdmin`, `Precio`),
  INDEX `administrador_idx` (`IdAdmin` ASC) VISIBLE,
  INDEX `user_idx` (`IdUsuario` ASC) VISIBLE,
  CONSTRAINT `administrador`
    FOREIGN KEY (`IdAdmin`)
    REFERENCES `bdm`.`chat` (`IdAdmin`),
  CONSTRAINT `articulo`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `bdm`.`producto` (`IdProducto`),
  CONSTRAINT `user`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `bdm`.`chat` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`imagen` (
  `IdImagen` INT(11) NOT NULL AUTO_INCREMENT,
  `imagen` BLOB NOT NULL,
  `Producto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdImagen`),
  INDEX `producto_idx` (`Producto` ASC) VISIBLE,
  CONSTRAINT `producto`
    FOREIGN KEY (`Producto`)
    REFERENCES `bdm`.`producto` (`IdProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdm`.`productocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdm`.`productocategoria` (
  `IdProducto` INT(11) NOT NULL,
  `IdCategoria` INT(11) NOT NULL,
  PRIMARY KEY (`IdProducto`, `IdCategoria`),
  INDEX `categoria_idx` (`IdCategoria` ASC) VISIBLE,
  CONSTRAINT `categoria`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `bdm`.`categoria` (`IdCategoria`),
  CONSTRAINT `product`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `bdm`.`producto` (`IdProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
